version: '3'
services:
  app1:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: ['node', 'src/index.js']
  app2:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: ['node', 'src/index.js']
  app3:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: ['node', 'src/index.js']
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '80:80'
    depends_on:
      - app1
      - app2
      - app3